linux: &linux
   os: linux
   dist: bionic
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=bincrafters/docker-centos-gcc48 ARCH=x86
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=bincrafters/docker-centos-gcc48 ARCH=x86_64
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=bincrafters/docker-centos-gcc48 ARCH=armv7
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=bincrafters/docker-centos-gcc48 ARCH=armv8
      - <<: *osx
        osx_image: xcode9
        env: ARCH=x86
      - <<: *osx
        osx_image: xcode9
        env: ARCH=x86_64
      - <<: *osx
        osx_image: xcode9
        env: ARCH=armv7
      - <<: *osx
        osx_image: xcode9
        env: ARCH=armv8

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
