build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          ARCH_BUILD: x86
          ARCH: x86
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          ARCH_BUILD: x86
          ARCH: x86_64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          ARCH_BUILD: x86
          ARCH: armv7
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          ARCH_BUILD: x86
          ARCH: armv8
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          ARCH_BUILD: x86_64
          ARCH: x86
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          ARCH_BUILD: x86_64
          ARCH: x86_64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          ARCH_BUILD: x86_64
          ARCH: armv7
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          ARCH_BUILD: x86_64
          ARCH: armv8

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
